# Generated by Django 2.2.1 on 2020-12-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('no', models.AutoField(db_column='clino', primary_key=True, serialize=False, verbose_name='客户编号')),
                ('name', models.CharField(db_column='cliname', max_length=32, unique=True, verbose_name='客户名称')),
            ],
            options={
                'verbose_name': '客户',
                'db_table': 'tb_client',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='公司编号')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='公司名称')),
                ('clients', models.ManyToManyField(to='app.Client')),
            ],
            options={
                'verbose_name': '公司',
                'db_table': 'tb_company',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('no', models.AutoField(db_column='drino', primary_key=True, serialize=False, verbose_name='司机编号')),
                ('name', models.CharField(db_column='driname', max_length=32, unique=True, verbose_name='司机名称')),
            ],
            options={
                'verbose_name': '司机',
                'db_table': 'tb_driver',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('no', models.AutoField(db_column='supno', primary_key=True, serialize=False, verbose_name='供应商编号')),
                ('name', models.CharField(db_column='supname', max_length=32, unique=True, verbose_name='供应商名称')),
            ],
            options={
                'verbose_name': '供应商',
                'db_table': 'tb_supplier',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('no', models.AutoField(db_column='salno', primary_key=True, serialize=False, verbose_name='销售人员编号')),
                ('name', models.CharField(db_column='salname', max_length=32, unique=True, verbose_name='销售人员名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
            ],
            options={
                'verbose_name': '销售人员',
                'db_table': 'tb_sale',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('no', models.AutoField(db_column='recno', primary_key=True, serialize=False, verbose_name='收款单编号')),
                ('receipt_date', models.DateField(verbose_name='收款日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('amount', models.DecimalField(db_column='recamout', decimal_places=2, max_digits=10, verbose_name='收款金额')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to='app.Client')),
            ],
            options={
                'verbose_name': '收款单',
                'db_table': 'tb_receipt',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('no', models.AutoField(db_column='payno', primary_key=True, serialize=False, verbose_name='付款单编号')),
                ('payment_date', models.DateField(verbose_name='付款日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('amount', models.DecimalField(db_column='payamout', decimal_places=2, max_digits=10, verbose_name='付款金额')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Supplier')),
            ],
            options={
                'verbose_name': '付款单',
                'db_table': 'tb_payment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('no', models.AutoField(db_column='ordno', primary_key=True, serialize=False, verbose_name='订单编号')),
                ('goods_price', models.DecimalField(db_column='ordamount', decimal_places=2, max_digits=5, verbose_name='商品单价')),
                ('number', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数量')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='销售佣金单价')),
                ('driver_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='运费单价')),
                ('order_date', models.DateField(verbose_name='订单日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Driver')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Sale')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Supplier')),
            ],
            options={
                'verbose_name': '订单',
                'db_table': 'tb_order',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='suppliers',
            field=models.ManyToManyField(to='app.Supplier'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User'),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('no', models.AutoField(db_column='debtno', primary_key=True, serialize=False, verbose_name='编号')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='欠款')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Company')),
            ],
            options={
                'verbose_name': '欠款',
                'db_table': 'tb_debt',
                'unique_together': {('company', 'client')},
            },
        ),
        migrations.CreateModel(
            name='Advpayment',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('adv_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预付款余额')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Supplier')),
            ],
            options={
                'verbose_name': '预付款',
                'db_table': 'tb_advpayment',
                'unique_together': {('supplier', 'company')},
            },
        ),
    ]
