# Generated by Django 2.2.1 on 2020-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buying_price',
            field=models.DecimalField(db_column='buying_price', decimal_places=2, default=200, max_digits=5, verbose_name='进价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='goods_price',
            field=models.DecimalField(db_column='saling_price', decimal_places=2, max_digits=5, verbose_name='售价'),
        ),
    ]
