# Generated by Django 2.2.1 on 2020-12-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201218_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.CharField(max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='remark',
            field=models.CharField(max_length=255, null=True, verbose_name='备注'),
        ),
    ]
