# Generated by Django 2.2.1 on 2020-12-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201218_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buying_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='运费单价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='销售佣金单价'),
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('no', models.AutoField(db_column='goodno', primary_key=True, serialize=False, verbose_name='商品编号')),
                ('name', models.CharField(db_column='goodname', max_length=32, verbose_name='商品名称')),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='进价')),
                ('end_date', models.DateField(verbose_name='失效时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Supplier')),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'tb_good',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Good'),
            preserve_default=False,
        ),
    ]
