# Generated by Django 2.2.1 on 2020-12-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201220_2158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='good',
            unique_together=set(),
        ),
    ]
