# Generated by Django 2.2.1 on 2020-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201221_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='start_date',
            field=models.DateField(default='2020-01-01', verbose_name='生效时间'),
            preserve_default=False,
        ),
    ]
