# Generated by Django 2.2.1 on 2020-12-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_good_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='supplier',
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='start_date',
            field=models.DateField(default='2020-01-01', verbose_name='生效时间'),
        ),
    ]
