# Generated by Django 2.2.1 on 2020-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201222_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_column='payamount', decimal_places=2, max_digits=10, verbose_name='付款金额'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(db_column='recamount', decimal_places=2, max_digits=10, verbose_name='收款金额'),
        ),
    ]
